name =input('What is your name?\n')
surname =input('What is your surname?\n') 
Education =int(input('What is your Education\n'))
Studentcode =int(input('What is your Studentcode\n'))
print(" %s." %name)
print(" %s." %surname)
print(" %s." %Education)
print(" %s." %Studentcode)